export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START_AUTO_LOGIN = 'AUTH_START_AUTO_LOGIN';

export const INIT_HOME_MOVIES = 'INIT_HOME_MOVIES';
export const SET_HOME_MOVIES = 'SET_HOME_MOVIES';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADDED_TO_WISHLIST = 'ADDED_TO_WISHLIST';

export const INIT_WISHLIST = 'INIT_WISHLIST';
export const SET_WISHLIST_MOVIES = 'SET_WISHLIST_MOVIES';
export const WISHLIST_REMOVE_MOVIE = 'WISHLIST_REMOVE_MOVIE';
export const WISHLIST_REMOVE_MOVIE_ENDING = 'WISHLIST_REMOVE_MOVIE_ENDING';